server:
  port: 8080
  error:
    include-message: never
    include-stacktrace: never

spring:
  application:
    name: marketflow-lab
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5433/marketflow}
    username: ${DB_USERNAME:marketflow}
    password: ${DB_PASSWORD:marketflow}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
        "[format_sql]": true
  flyway:
    enabled: true
  jackson:
    default-property-inclusion: non_null

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  info:
    env:
      enabled: true

info:
  app:
    name: marketflow-lab
    phase: 02-persistence-jpa-transactions
    description: MarketFlow Senior Java Cloud Lab - Phase 2

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{36} - %msg%n"
  level:
    "[com.gustavo.marketflow]": DEBUG
    "[org.springframework.web]": INFO
